### PR TITLE
Reduce log level when refreshing certificates

### LINKED ISSUE #75: Superfluous error messages when refreshing trust store
Since the fix of #73, the rabbitmq-trust-store plugin spams the log with unnecessary error messages during normal operation: 

> 2020-05-03 03:24:34.773 [error] <0.843.0> Trust store will attempt to refresh certificates...
> 2020-05-03 03:25:04.788 [error] <0.843.0> Trust store will attempt to refresh certificates...
> 2020-05-03 03:25:34.804 [error] <0.843.0> Trust store will attempt to refresh certificates...
> 2020-05-03 03:26:04.821 [error] <0.843.0> Trust store will attempt to refresh certificates...
> 2020-05-03 03:26:34.839 [error] <0.843.0> Trust store will attempt to refresh certificates...
> 2020-05-03 03:27:04.853 [error] <0.843.0> Trust store will attempt to refresh certificates...

These  should be logged at debug level instead.

### PR DESCRIPTION
**Pull request by mgrafl**
Log at error level was superfluous during normal operation. 
Fixes #75

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mgrafl Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-trust-store&pullRequestId=76)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-trust-store&pullRequestId=76) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mgrafl Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-trust-store&pullRequestId=76)!

**Comment by michaelklishin** [comment]
Thank you!

**Comment by michaelklishin** [comment]
Backported to `v3.8.x`.

**Comment by michaelklishin** [comment]
Backported to `v3.7.x` just in case.

**Pull request merged**
