### PR TITLE
Function to list loaded certs

### LINKED ISSUE #31: Include ability to list trusted certs
Currently, it is possible to see which certs are loaded by the trust store plug-in by executing 

`rabbitmqctl eval 'ets:tab2list(trust_store_whitelist).'`

Can this be improved to show:
- filename (from where the cert was loaded)
- certificate serial number (hex is preferred, but decimal may also be included)
- certificate DN
- certificate issuing CA
- certificate timeframe (issued/expired)

### PR DESCRIPTION
**Pull request by kjnilsson**
I've updated the PR to return a string of all certificates.

Fixes #31

### CODE REVIEW

**Comment by michaelklishin** [comment]
I don't think tuples are very human-friendly. We should output reasonably formatted text and indicate what each value is, e.g.

```
Name: cert.pem"",1,,
Serial: 1
Subject: O=client,CN=snowman.local
Issuer: L=87613,CN=MyTestRootCA
Validity:2016-05-24T15:28:25Z - 2026-05-22T15:28:25Z

Name: …
Serial: …
Subject: …
Issuer: …
Validity: …
```

This is much closer to how `openssl x509` outputs certificate details.

**Comment by michaelklishin** [comment]
@kjnilsson I think the function in question will have to print to stdout until 3.7.0 which should have extensible CLI tools.

**Comment by kjnilsson** [comment]
@michaelklishin is there a way to marshal stdout back to the `rabbitmqctl` node? I tried it and it just printed it on the broker node.

**Comment by michaelklishin** [comment]
Yeah, that's tricky. We can combine 2 functions: one for returning certificate data, one for formatting it, and one list comprehension. It's a matter of documenting how to use them in a single shell command.

**Comment by kjnilsson** [comment]
I have a stash that returns a big string with pretty much exactly the format you suggested above but you'd have to do `rabbitmqctl eval 'io:format(rabbit_trust_store:list())'` for it to print nicely. Perhaps this is ok.

**Comment by michaelklishin** [comment]
That's fine. We can also develop a trust store management UI plugin that'd
list them in a more sensible way (not a part of this issue, of course).

On Tue, Jun 21, 2016 at 1:55 PM, Karl Nilsson <notifications@github.com>
wrote:

> I have a stash that returns a big string with pretty much exactly the
> format you suggested above but you'd have to do rabbitmqctl eval
> 'io:format(rabbit_trust_store:list())' for it to print nicely. Perhaps
> this is ok.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rabbitmq/rabbitmq-trust-store/pull/33#issuecomment-227406374>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAEQpg4IJGq1j9mslqdHz-GK17JH6L0ks5qN8MSgaJpZM4I6hsq>
> .
>



-- 
MK

Staff Software Engineer, Pivotal/RabbitMQ

**Comment by kjnilsson** [comment]
ok cool - let's go with that.

**Pull request merged**
